name: Publish FFmpeg
on:
  release:
    types: [published]
jobs:
  publish_ffmpeg:
    runs-on: ubuntu-latest
    steps:      
      - name: Installing Some dependencies
        run: |
          sudo apt update
          sudo apt install p7zip curl unzip tar gzip -y

      - name: Downloading Windows x64 FFMPEG
        run: |
          mkdir temp
          cd temp
          curl -L https://www.gyan.dev/ffmpeg/builds/ffmpeg-release-essentials.7z -o windows.7z
          7zr x windows.7z
          cp ffmpeg-*_build/bin/ffmpeg.exe ../ffmpeg-win32-x64.exe
          cd ..
          rm -r temp
          gzip ffmpeg-win32-x64.exe

      - name: Downloading Windows ia32 FFMPEG
        run: |
          mkdir temp
          cd temp
          curl -L https://github.com/sudo-nautilus/FFmpeg-Builds-Win32/releases/download/latest/ffmpeg-master-latest-win32-gpl.zip -o windows.zip
          unzip windows.zip
          cp ffmpeg-*-gpl/bin/ffmpeg.exe ../ffmpeg-win32-ia32.exe
          cd ..
          rm -r temp
          gzip ffmpeg-win32-ia32.exe
      
      - name: Downloading Linux x64 FFMPEG
        run: |
          mkdir temp
          cd temp
          curl --connect-timeout 5 --max-time 10 --retry 5 --retry-delay 0 --retry-max-time 40 -L https://johnvansickle.com/ffmpeg/builds/ffmpeg-git-amd64-static.tar.xz -o linux.tar.xz
          tar xvf linux.tar.xz
          cp ffmpeg-*-static/ffmpeg ../ffmpeg-linux-x64
          cd ..
          rm -r temp
          gzip ffmpeg-linux-x64
      
      - name: Downloading Linux ia32 FFMPEG
        run: |
          mkdir temp
          cd temp
          curl -L https://johnvansickle.com/ffmpeg/builds/ffmpeg-git-i686-static.tar.xz -o linux.tar.xz
          tar xvf linux.tar.xz
          cp ffmpeg-*-static/ffmpeg ../ffmpeg-linux-ia32
          cd ..
          rm -r temp
          gzip ffmpeg-linux-ia32
      
      - name: Downloading Linux arm FFMPEG
        run: |
          mkdir temp
          cd temp
          curl -L https://johnvansickle.com/ffmpeg/builds/ffmpeg-git-armhf-static.tar.xz -o linux.tar.xz
          tar xvf linux.tar.xz
          cp ffmpeg-*-static/ffmpeg ../ffmpeg-linux-arm
          cd ..
          rm -r temp
          gzip ffmpeg-linux-arm
      
      - name: Downloading Linux arm64 FFMPEG
        run: |
          mkdir temp
          cd temp
          curl -L https://johnvansickle.com/ffmpeg/builds/ffmpeg-git-arm64-static.tar.xz -o linux.tar.xz
          tar xvf linux.tar.xz
          cp ffmpeg-*-static/ffmpeg ../ffmpeg-linux-arm64
          cd ..
          rm -r temp
          gzip ffmpeg-linux-arm64

      - name: Downloading MacOs x64 FFMPEG
        run: |
          mkdir temp
          cd temp
          curl -L https://evermeet.cx/ffmpeg/ffmpeg-4.4.1.7z -o darwin.7z
          7zr x darwin.7z
          cp ffmpeg ../ffmpeg-darwin-x64
          cd ..
          rm -r temp
          gzip ffmpeg-darwin-x64

      - name: Downloading MacOs arm64 FFMPEG
        run: |
          mkdir temp
          cd temp
          curl -L https://www.osxexperts.net/FFmpeg441.zip -o darwin.zip
          unzip darwin.zip
          cp ffmpeg ../ffmpeg-darwin-arm64
          cd ..
          rm -r temp
          gzip ffmpeg-darwin-arm64

      - name: Upload Release [ FFmpeg Windows x64 ]
        uses: JasonEtco/upload-to-release@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          args: ffmpeg-win32-x64.exe.gz application/gzip

      - name: Upload Release [ FFmpeg Windows ia32 ]
        uses: JasonEtco/upload-to-release@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          args: ffmpeg-win32-ia32.exe.gz application/gzip
      
      - name: Upload Release [ FFmpeg Linux x64 ]
        uses: JasonEtco/upload-to-release@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          args: ffmpeg-linux-x64.gz application/gzip
      
      - name: Upload Release [ FFmpeg Linux ia32 ]
        uses: JasonEtco/upload-to-release@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          args: ffmpeg-linux-ia32.gz application/gzip
      
      - name: Upload Release [ FFmpeg Linux arm ]
        uses: JasonEtco/upload-to-release@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          args: ffmpeg-linux-arm.gz application/gzip
      
      - name: Upload Release [ FFmpeg Linux arm64 ]
        uses: JasonEtco/upload-to-release@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          args: ffmpeg-linux-arm64.gz application/gzip
      
      - name: Upload Release [ FFmpeg MacOs x64 ]
        uses: JasonEtco/upload-to-release@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          args: ffmpeg-darwin-x64.gz application/gzip
      
      - name: Upload Release [ FFmpeg MacOs arm64 ]
        uses: JasonEtco/upload-to-release@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          args: ffmpeg-darwin-arm64.gz application/gzip
